-- hannote 评论点赞表（PostgreSQL）
-- 在数据库 hannote 中执行
-- 属主：hannote-comment 服务（CommentLikeDO）
CREATE TABLE IF NOT EXISTS t_comment_like (
    id           BIGINT     NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT     NOT NULL,
    comment_id   BIGINT     NOT NULL,
    create_time  TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX IF NOT EXISTS uk_comment_like_user_comment ON t_comment_like(user_id, comment_id);
CREATE INDEX IF NOT EXISTS idx_comment_like_comment_id ON t_comment_like(comment_id);

COMMENT ON TABLE  t_comment_like             IS '评论点赞表';
COMMENT ON COLUMN t_comment_like.id          IS '主键 ID';
COMMENT ON COLUMN t_comment_like.user_id     IS '用户 ID';
COMMENT ON COLUMN t_comment_like.comment_id  IS '被点赞的评论 ID';
COMMENT ON COLUMN t_comment_like.create_time IS '点赞时间';
