-- hannote 用户粉丝表（PostgreSQL）
-- 在数据库 hannote 中执行
-- ��记录「用户 B 拥有粉丝用户 A」的粉丝关系（关注表的反向视图）。
-- 主键使用 PostgreSQL 库自增（GENERATED BY DEFAULT AS IDENTITY），不走分布式 ID 服务。
-- 关系记录不做逻辑删除：被取关时直接物理删除，故无 is_deleted 字段。

CREATE TABLE IF NOT EXISTS t_fans (
    id             BIGINT     NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id        BIGINT     NOT NULL,
    fans_user_id   BIGINT     NOT NULL,
    create_time    TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 联合唯一索引：保证幂等（MQ 重复消费最终只落一条粉丝关系）。
-- ��按最左匹配原则，(user_id, fans_user_id) 亦可覆盖仅按 user_id 查询
-- 「谁关注了我」的核心场景，故无需再单独建 user_id 普通索引。
CREATE UNIQUE INDEX IF NOT EXISTS uk_fans_user_fans ON t_fans(user_id, fans_user_id);

COMMENT ON TABLE  t_fans              IS '用户粉丝表';
COMMENT ON COLUMN t_fans.id           IS '主键 ID';
COMMENT ON COLUMN t_fans.user_id      IS '用户 ID';
COMMENT ON COLUMN t_fans.fans_user_id IS '粉丝的用户 ID';
COMMENT ON COLUMN t_fans.create_time  IS '创建时间';
