-- hannote 用户关注表（PostgreSQL）
-- 在数据库 hannote 中执行
-- ��记录「用户 A 关注了用户 B」的关注关系，一对多。
-- 主键使用 PostgreSQL 库自增（GENERATED BY DEFAULT AS IDENTITY），不走分布式 ID 服务。
-- 关系记录不做逻辑删除：取关时直接物理删除，故无 is_deleted 字段。

CREATE TABLE IF NOT EXISTS t_following (
    id                 BIGINT     NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id            BIGINT     NOT NULL,
    following_user_id  BIGINT     NOT NULL,
    create_time        TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 按 user_id 查询「我关注了谁」是核心场景，建索引提升查询性能
CREATE INDEX IF NOT EXISTS idx_following_user_id ON t_following(user_id);

COMMENT ON TABLE  t_following                   IS '用户关注表';
COMMENT ON COLUMN t_following.id                IS '主键 ID';
COMMENT ON COLUMN t_following.user_id           IS '用户 ID';
COMMENT ON COLUMN t_following.following_user_id IS '关注的用户 ID';
COMMENT ON COLUMN t_following.create_time       IS '创建时间（关注时间，也用于关注列表排序）';
