-- 发送失败的 MQ 兜底表（属主：hannote-comment）
-- 评论发布异步发 MQ 多次重试仍失败的消息落此表，由 PowerJob 定时扫表重发，成功后物理删除。
CREATE TABLE IF NOT EXISTS t_mq_send_fail
(
    id              BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic           VARCHAR(128) NOT NULL,
    body            TEXT         NOT NULL,
    retry_count     INT          NOT NULL DEFAULT 0,
    next_retry_time TIMESTAMP    NOT NULL DEFAULT now(),
    status          SMALLINT     NOT NULL DEFAULT 0, -- 0 待重发 / 1 处理中
    create_time     TIMESTAMP    NOT NULL DEFAULT now(),
    update_time     TIMESTAMP    NOT NULL DEFAULT now()
);

-- 扫表索引：按 (status, next_retry_time) 捞取到期待重发记录
CREATE INDEX IF NOT EXISTS idx_mq_send_fail_scan ON t_mq_send_fail (status, next_retry_time);

COMMENT ON TABLE t_mq_send_fail IS '发送失败的 MQ 兜底表';
COMMENT ON COLUMN t_mq_send_fail.topic IS '目标 Topic';
COMMENT ON COLUMN t_mq_send_fail.body IS '消息体 JSON';
COMMENT ON COLUMN t_mq_send_fail.retry_count IS '已补偿重发次数';
COMMENT ON COLUMN t_mq_send_fail.next_retry_time IS '下次可重发时间（退避）';
COMMENT ON COLUMN t_mq_send_fail.status IS '状态：0 待重发 / 1 处理中';
