-- hannote 笔记点赞表（PostgreSQL）
-- 在数据库 hannote 中执行
-- 属主：hannote-note 服务（NoteLikeDO）
CREATE TABLE IF NOT EXISTS t_note_like (
    id           BIGINT     NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT     NOT NULL,
    note_id      BIGINT     NOT NULL,
    create_time  TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status       SMALLINT   NOT NULL DEFAULT 0
);

-- (user_id, note_id) 联合唯一索引：保证同一用户不能重复点赞同一笔记（幂等）
CREATE UNIQUE INDEX IF NOT EXISTS uk_note_like_user_note ON t_note_like(user_id, note_id);

COMMENT ON TABLE  t_note_like             IS '笔记点赞表';
COMMENT ON COLUMN t_note_like.id          IS '主键 ID';
COMMENT ON COLUMN t_note_like.user_id     IS '用户 ID';
COMMENT ON COLUMN t_note_like.note_id     IS '被点赞的笔记 ID';
COMMENT ON COLUMN t_note_like.create_time IS '点赞时间（用于排序）';
COMMENT ON COLUMN t_note_like.status      IS '点赞状态（0：取消点赞 1：点赞）';
