-- hannote 笔记计数表（PostgreSQL）
-- 在数据库 hannote 中执行
-- 属主：hannote-count 服务（NoteCountDO）
CREATE TABLE IF NOT EXISTS t_note_count (
    id             BIGINT  NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    note_id        BIGINT  NOT NULL,
    like_total     BIGINT  DEFAULT 0,
    collect_total  BIGINT  DEFAULT 0,
    comment_total  BIGINT  DEFAULT 0
);

-- note_id 唯一索引：一篇笔记一行计数，提升查询效率
CREATE UNIQUE INDEX IF NOT EXISTS uk_note_count_note_id ON t_note_count(note_id);

COMMENT ON TABLE  t_note_count               IS '笔记计数表';
COMMENT ON COLUMN t_note_count.id            IS '主键 ID';
COMMENT ON COLUMN t_note_count.note_id       IS '笔记 ID';
COMMENT ON COLUMN t_note_count.like_total    IS '获得点赞总数';
COMMENT ON COLUMN t_note_count.collect_total IS '获得收藏总数';
COMMENT ON COLUMN t_note_count.comment_total IS '被评论总数（评论服务未建，先留位）';
