-- hannote 笔记收藏表（PostgreSQL）
-- 在数据库 hannote 中执行
-- 属主：hannote-note 服务（NoteCollectionDO）
CREATE TABLE IF NOT EXISTS t_note_collection (
    id           BIGINT     NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id      BIGINT     NOT NULL,
    note_id      BIGINT     NOT NULL,
    create_time  TIMESTAMP  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    status       SMALLINT   NOT NULL DEFAULT 0
);

-- (user_id, note_id) 联合唯一索引：保证同一用户不能重复收藏同一笔记（幂等）
CREATE UNIQUE INDEX IF NOT EXISTS uk_note_collection_user_note ON t_note_collection(user_id, note_id);

COMMENT ON TABLE  t_note_collection             IS '笔记收藏表';
COMMENT ON COLUMN t_note_collection.id          IS '主键 ID';
COMMENT ON COLUMN t_note_collection.user_id     IS '用户 ID';
COMMENT ON COLUMN t_note_collection.note_id     IS '被收藏的笔记 ID';
COMMENT ON COLUMN t_note_collection.create_time IS '收藏时间（用于排序）';
COMMENT ON COLUMN t_note_collection.status      IS '收藏状态（0：取消收藏 1：收藏）';
