-- hannote 用户计数表（PostgreSQL）
-- 在数据库 hannote 中执行
-- 属主：hannote-count 服务（UserCountDO）
CREATE TABLE IF NOT EXISTS t_user_count (
    id               BIGINT  NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id          BIGINT  NOT NULL,
    fans_total       BIGINT  DEFAULT 0,
    following_total  BIGINT  DEFAULT 0,
    note_total       BIGINT  DEFAULT 0,
    like_total       BIGINT  DEFAULT 0,
    collect_total    BIGINT  DEFAULT 0
);

-- user_id 唯一索引：一个用户一行计数，提升查询效率
CREATE UNIQUE INDEX IF NOT EXISTS uk_user_count_user_id ON t_user_count(user_id);

COMMENT ON TABLE  t_user_count                 IS '用户计数表';
COMMENT ON COLUMN t_user_count.id              IS '主键 ID';
COMMENT ON COLUMN t_user_count.user_id         IS '用户 ID';
COMMENT ON COLUMN t_user_count.fans_total      IS '粉丝总数';
COMMENT ON COLUMN t_user_count.following_total IS '关注总数';
COMMENT ON COLUMN t_user_count.note_total      IS '发布笔记总数';
COMMENT ON COLUMN t_user_count.like_total      IS '获得点赞总数';
COMMENT ON COLUMN t_user_count.collect_total   IS '获得收藏总数';
