<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.hanserwei</groupId>
        <artifactId>hannote</artifactId>
        <version>${revision}</version>
    </parent>

    <artifactId>hannote-user-relation</artifactId>
    <packaging>pom</packaging>

    <name>${project.artifactId}</name>
    <description>hannote 用户关系服务（聚合模块）：关注/粉丝相关业务。作者：Hanserwei</description>

    <modules>
        <module>hannote-user-relation-api</module>
        <module>hannote-user-relation-biz</module>
    </modules>

</project>
