package com.hanserwei.relation.domain.dataobject;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * 用户粉丝表数据对象.
 *
 * <p>对应数据表 {@code t_fans}。记录「用户 {@code userId} 拥有粉丝
 * {@code fansUserId}」的粉丝关系，是关注表的反向视图。关系记录不做逻辑删除，
 * 被取关时直接物理删除，故不含 {@code is_deleted} 字段。
 *
 * <p>主键由 PostgreSQL 库自增（{@code GENERATED BY DEFAULT AS IDENTITY}）生成，
 * 使用 {@link IdType#AUTO}；不走分布式 ID 服务。
 *
 * @author hanserwei
 * @date 2026/07/10
 * @since 0.0.1
 */
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@TableName("t_fans")
public class FansDO {

    /** 主键 ID（库自增） */
    @TableId(type = IdType.AUTO)
    private Long id;

    /** 用户 ID（被关注方） */
    private Long userId;

    /** 粉丝的用户 ID（关注发起方） */
    private Long fansUserId;

    /** 创建时间 */
    private LocalDateTime createTime;
}
