package com.hanserwei.relation.domain.dataobject;

import com.baomidou.mybatisplus.annotation.IdType;
import com.baomidou.mybatisplus.annotation.TableId;
import com.baomidou.mybatisplus.annotation.TableName;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;

/**
 * 用户关注表数据对象.
 *
 * <p>对应数据表 {@code t_following}。记录「用户 {@code userId} 关注了用户
 * {@code followingUserId}」的关注关系，一对多。关系记录不做逻辑删除，
 * 取关时直接物理删除，故不含 {@code is_deleted} 字段。
 *
 * <p>主键由 PostgreSQL 库自增（{@code GENERATED BY DEFAULT AS IDENTITY}）生成，
 * 使用 {@link IdType#AUTO}；不走分布式 ID 服务。
 *
 * @author hanserwei
 * @date 2026/07/10
 * @since 0.0.1
 */
@Data
@Builder
@AllArgsConstructor
@NoArgsConstructor
@TableName("t_following")
public class FollowingDO {

    /** 主键 ID（库自增） */
    @TableId(type = IdType.AUTO)
    private Long id;

    /** 用户 ID（关注发起方） */
    private Long userId;

    /** 关注的用户 ID（被关注方） */
    private Long followingUserId;

    /** 创建时间（关注时间，也用于关注列表排序） */
    private LocalDateTime createTime;
}
