server:
  port: 8081

spring:
  application:
    name: hannote-oss
  profiles:
    active: dev
  threads:
    virtual:
      enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
